# Generated by Django 5.2.7 on 2025-10-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Khách hàng'), ('RECEPTIONIST', 'Lễ tân'), ('CRM_STAFF', 'Nhân viên CSKH'), ('ADMIN', 'Quản lý')], default='CUSTOMER', max_length=50),
        ),
    ]
