# Generated by Django 5.2.7 on 2025-10-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Khách hàng'), ('STAFF', 'Nhân viên'), ('ADMIN', 'Quản lý')], default='CUSTOMER', max_length=50),
        ),
    ]
