# Generated by Django 5.2.7 on 2025-11-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Khách hàng'), ('RECEPTION', 'Lễ tân'), ('SUPPORT', 'CSKH'), ('ADMIN', 'Quản lý')], default='CUSTOMER', max_length=50),
        ),
    ]
