# Generated by Django 5.2.7 on 2025-10-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Ảnh minh họa'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_categories/', verbose_name='Ảnh minh họa'),
        ),
    ]
