# Generated by Django 5.2.7 on 2025-10-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_image_servicecategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/services/', verbose_name='Ảnh minh họa'),
        ),
    ]
