# Generated by Django 5.2.7 on 2025-10-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Không hoạt động'), ('MAINTENANCE', 'Đang bảo trì')], default='ACTIVE', max_length=20, verbose_name='Trạng thái dịch vụ'),
        ),
    ]
