# Generated by Django 5.2.7 on 2025-11-06 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='highlights',
            field=models.TextField(blank=True, help_text='Mỗi điểm nổi bật trên một dòng (sẽ hiển thị dạng bullet point).', verbose_name='Điểm nổi bật'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_unit',
            field=models.CharField(blank=True, help_text="Ví dụ: 'mỗi khách', 'mỗi giờ', 'trọn gói'", max_length=50, verbose_name='Đơn vị tính giá'),
        ),
        migrations.AddField(
            model_name='service',
            name='terms_conditions',
            field=models.TextField(blank=True, help_text='Mỗi điều khoản trên một dòng.', verbose_name='Điều khoản & Điều kiện'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả chung'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/service_categories/', verbose_name='Ảnh minh họa'),
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/services/gallery/', verbose_name='Ảnh')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Văn bản thay thế')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='services.service', verbose_name='Dịch vụ')),
            ],
        ),
    ]
