# Generated by Django 5.2.7 on 2025-10-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True, verbose_name='Số phòng')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Còn trống'), ('OCCUPIED', 'Đang có khách'), ('CLEANING', 'Đang dọn dẹp')], default='AVAILABLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RoomClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên hạng phòng')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá cơ bản/đêm')),
                ('area', models.CharField(max_length=50, verbose_name='Diện tích')),
                ('amenities', models.TextField(help_text='Mỗi tiện ích cách nhau bởi dấu phẩy', verbose_name='Tiện ích')),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_classes/', verbose_name='Ảnh hạng phòng')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên loại phòng')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chung')),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_types/', verbose_name='Ảnh đại diện')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_full_name', models.CharField(blank=True, max_length=255)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_phone_number', models.CharField(blank=True, max_length=20)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('additional_services', models.ManyToManyField(blank=True, to='services.service', verbose_name='Dịch vụ đi kèm')),
            ],
        ),
    ]
