# Generated by Django 5.1.4 on 2025-10-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('PAY_LATER', 'Thanh toán khi nhận phòng'), ('BANK_TRANSFER', 'Chuyển khoản ngân hàng')], default='PAY_LATER', max_length=20, verbose_name='Phương thức thanh toán'),
        ),
    ]
