# Generated by Django 5.2.7 on 2025-10-12 15:36

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Quốc tịch khách vãng lai'),
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='payment_proofs/', verbose_name='Ảnh bằng chứng')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proof', to='booking.booking')),
            ],
        ),
    ]
