# Generated by Django 5.2.7 on 2025-10-13 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_guest_nationality_paymentproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_assigned', to='booking.room', verbose_name='Phòng đã gán'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('CHECKED_IN', 'Đã nhận phòng'), ('COMPLETED', 'Đã hoàn thành'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20),
        ),
    ]
