# Generated by Django 5.2.7 on 2025-10-21 08:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_assigned_room_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
