# Generated by Django 5.2.7 on 2025-10-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_booking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, verbose_name='Yêu cầu đặc biệt'),
        ),
    ]
