# Generated by Django 5.2.7 on 2025-10-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_special_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tiền phòng'),
        ),
        migrations.AddField(
            model_name='booking',
            name='services_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tiền dịch vụ'),
        ),
    ]
