# Generated by Django 5.2.7 on 2025-10-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_room_price_booking_services_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Còn trống'), ('OCCUPIED', 'Đang có khách'), ('CLEANING', 'Đang dọn dẹp'), ('MAINTENANCE', 'Đang bảo trì')], default='AVAILABLE', max_length=20, verbose_name='Trạng thái phòng'),
        ),
    ]
