# Generated by Django 5.2.7 on 2025-11-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Chuyển khoản ngân hàng')], default='BANK_TRANSFER', max_length=20, verbose_name='Phương thức thanh toán'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='image',
            field=models.ImageField(upload_to='media/payment_proofs/', verbose_name='Ảnh bằng chứng'),
        ),
        migrations.AlterField(
            model_name='roomclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/room_classes/', verbose_name='Ảnh hạng phòng'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/room_types/', verbose_name='Ảnh đại diện'),
        ),
    ]
