# Generated by Django 5.2.7 on 2025-11-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Đã khóa (không thể sửa)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm tải chứng từ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Đang xem xét'), ('PENDING_PAYMENT', 'Chờ thanh toán'), ('READY_FOR_PAYMENT', 'Sẵn sàng thanh toán'), ('PAYMENT_PENDING_VERIFICATION', 'Chờ xác nhận TT'), ('PAID', 'Đã thanh toán'), ('CONFIRMED', 'Đã xác nhận'), ('CHECKED_IN', 'Đã nhận phòng'), ('COMPLETED', 'Đã hoàn thành'), ('EXPIRED', 'Đã hết hạn'), ('CANCELLED', 'Đã hủy')], default='PENDING_REVIEW', max_length=30),
        ),
    ]
