# Generated by Django 5.2.7 on 2025-11-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_booking_is_locked_booking_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adults',
            field=models.PositiveIntegerField(default=1, verbose_name='Số người lớn'),
        ),
        migrations.AddField(
            model_name='booking',
            name='children',
            field=models.PositiveIntegerField(default=0, verbose_name='Số trẻ em'),
        ),
    ]
