# Generated by Django 5.2.7 on 2025-11-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_booking_adults_booking_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomclass',
            name='max_occupancy',
            field=models.PositiveIntegerField(default=2, help_text='Số người lớn + trẻ em tối đa mà phòng này có thể chứa.', verbose_name='Sức chứa tối đa'),
        ),
    ]
