# Generated by Django 5.2.7 on 2025-10-16 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='title',
        ),
        migrations.AddField(
            model_name='ticket',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email khách vãng lai'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='guest_full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Họ tên khách vãng lai'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='guest_phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='SĐT khách vãng lai'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng (nếu có)'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'Mới'), ('IN_PROGRESS', 'Đang xử lý'), ('RESOLVED', 'Đã hoàn thành')], default='NEW', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('CONSULTATION', 'Tư vấn Dịch vụ'), ('BOOKING_SUPPORT', 'Hỗ trợ Đặt phòng'), ('OTHER', 'Yêu cầu Khác')], max_length=20, verbose_name='Loại yêu cầu'),
        ),
    ]
