# Generated by Django 5.2.7 on 2025-10-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_ticket_title_ticket_guest_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'Mới'), ('IN_PROGRESS', 'Đang xử lý'), ('AWAITING_STAFF', 'Chờ Nhân viên Phản hồi'), ('RESOLVED', 'Đã hoàn thành')], default='NEW', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
