# Generated by Django 5.2.7 on 2025-10-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ticket_attachments/', verbose_name='Tệp đính kèm'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='incident_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xảy ra vụ việc'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('CONSULTATION', 'Tư vấn Dịch vụ'), ('BOOKING_SUPPORT', 'Hỗ trợ Đặt phòng'), ('COMPLAINT', 'Khiếu nại'), ('OTHER', 'Yêu cầu Khác')], max_length=20, verbose_name='Loại yêu cầu'),
        ),
    ]
