# Generated by Django 5.2.7 on 2025-10-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_ticket_attachment_ticket_incident_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='complaint_type',
            field=models.CharField(blank=True, choices=[('ROOM_QUALITY', 'Về chất lượng phòng'), ('STAFF_ATTITUDE', 'Về thái độ nhân viên'), ('SERVICE_ISSUES', 'Về chất lượng dịch vụ'), ('BILLING_ERROR', 'Về sai sót thanh toán'), ('OTHER', 'Vấn đề khác')], max_length=20, null=True, verbose_name='Loại khiếu nại'),
        ),
    ]
