# Generated by Django 5.2.7 on 2025-10-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_ticket_complaint_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketAttachment',
        ),
    ]
