# Generated by Django 5.2.7 on 2025-11-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_ticket_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution_details',
            field=models.TextField(blank=True, help_text='Ghi lại nguyên nhân, giải pháp, đền bù (nếu có) sau khi ticket đã hoàn thành.', null=True, verbose_name='Kết quả xử lý (cuối cùng)'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='media/ticket_attachments/', verbose_name='Tệp đính kèm'),
        ),
    ]
