# Tên của quy trình CI, sẽ hiển thị trên tab "Actions" của GitHub
name: Django CI

# Quy định khi nào quy trình này sẽ được kích hoạt
on:
  push:
    branches: [ "main" ] # Chạy mỗi khi có push lên nhánh main
  pull_request:
    branches: [ "main" ] # Chạy mỗi khi có pull request vào nhánh main

# Định nghĩa các công việc cần làm
jobs:
  build:
    # Chọn hệ điều hành để chạy (phiên bản Ubuntu mới nhất)
    runs-on: ubuntu-latest

    # Các bước thực thi công việc
    steps:
      # Bước 1: Lấy code từ repository về máy ảo
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Cài đặt phiên bản Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      # Bước 3: Cài đặt các thư viện từ file requirements.txt
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Bước 4: Chạy các bài test của Django
      # Django tự động tạo một bài test đơn giản khi bạn tạo app
      - name: Run Tests
        run: |
          python manage.py test